routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/getApp', 'Admin\CareersController@getData');

Route::group(['middleware' => 'auth'], function () {

    Route::get('/admin-panel', 'Admin\DashboardController@index');

    Route::group(['middleware' => ['auth'], 'prefix' => "admin-panel", 'namespace' => 'Admin'], function () {


        // Routing Users
        Route::resource('/users', 'UserController');
        Route::post('user-delete/{id}', 'UserController@destroy')->name("user-delete");
        Route::get('user-restore/{id}', 'UserController@restore_user')->name('user-restore');
        Route::get('user-deleted', 'UserController@get_deleted_user')->name('users.deleted');

        // Routing Coupons
        Route::resource('/coupons', 'CouponsController');
        Route::post('coupon_delete/{id}', 'CouponsController@destroy')->name("coupon-delete");
        Route::get('coupon-restore/{id}', 'CouponsController@restore_coupon')->name('coupon-restore');
        Route::get('coupon-deleted', 'CouponsController@get_deleted_coupon')->name('coupon.deleted');


        // Routing Careers
        Route::resource('/careers', 'CareersController');
        Route::post('career-delete/{id}', 'CareersController@destroy')->name("career-delete");
        Route::get('career-restore/{id}', 'CareersController@restore_career')->name('career-restore');
        Route::get('career-deleted', 'CareersController@get_deleted_career')->name('career.deleted');


        // Routing Career Applicant
        Route::resource('/career-applicant', 'CareerApplicantsController');
        Route::post('career-applicant-delete/{id}', 'CareerApplicantsController@destroy')->name("career-applicant-delete");
        Route::get('career-applicant.download/{id}', 'CareerApplicantsController@download')->name("career-applicant.download");
        Route::get('career-applicant-restore/{id}', 'CareerApplicantsController@restore_career_applicant')->name('career-applicant-restore');
        Route::get('career-applicant-deleted', 'CareerApplicantsController@get_deleted_career_applicant')->name('career-applicant.deleted');


        // Routing Users
        Route::resource('/authorization', 'AuthorizationController');
        Route::post('authorization-delete/{id}', 'AuthorizationController@destroy')->name("authorization-delete");

        // Routing Winners
        Route::post('winners', 'winners@winners')->name("get-winner");
        Route::get('get-winner', 'winners@get_winner')->name("get-all-winner");


        // Routing Categories
        Route::resource('/categories', 'CategoryController');
        Route::post('category-delete/{id}', 'CategoryController@destroy')->name("categories-delete");
        Route::get('category-restore/{id}', 'CategoryController@restore_category')->name('category-restore');
        Route::get('category-deleted', 'CategoryController@get_deleted_category')->name('category.deleted');

        // Routing Offers
        Route::resource('/offers', 'OffersController');
        Route::post('offer-delete/{id}', 'OffersController@destroy')->name("offers-delete");
        Route::get('offer-restore/{id}', 'OffersController@restore_offer')->name('offer-restore');
        Route::get('offer-deleted', 'OffersController@get_deleted_offer')->name('offer.deleted');

        // Routing Donations
        Route::get('/donations', 'DonationController@index')->name("donation");


        // Routing Subscribers
        Route::resource('/messages', 'MessagesController');
        Route::post('message-delete/{id}', 'MessagesController@destroy')->name("messages-delete");

        // Routing Settings
        Route::get('settings/edit', 'SettingController@edit')->name("settings.edit");
        Route::post('settings/update', 'SettingController@update')->name("settings.update");


        // Routing Products
        Route::resource('/products', 'ProductsController');
        Route::post('product-delete/{id}', 'ProductsController@destroy')->name("products-delete");
        Route::PUT('image_update/{id}', 'ProductsController@uploadImages')->name('image.upload');
        Route::get('image_delete/{id}', 'ProductsController@deleteImage')->name('image.delete');
        Route::get('product-restore/{id}', 'ProductsController@restore_product')->name('product-restore');
        Route::get('product-deleted', 'ProductsController@get_deleted_product')->name('product.deleted');

        // Routing Rewards
        
        Route::resource('/rewards', 'RewardsController');
        Route::post('reward-delete/{id}', 'RewardsController@destroy')->name("rewards-delete");
        Route::get('reward-restore/{id}', 'RewardsController@restore_reward')->name('reward-restore');
        Route::get('reward-deleted', 'RewardsController@get_deleted_reward')->name('reward.deleted');

        // Routing Sliders
        Route::resource('/sliders', 'SlidersController');
        Route::post('slider-delete/{id}', 'SlidersController@destroy')->name("sliders-delete");
        Route::PUT('imageSlider_update/{id}', 'SlidersController@upload_Images')->name('imageSlider.upload');
        Route::get('imageSlider_delete/{id}', 'SlidersController@delete_Image')->name('imageSlider.delete');
        Route::get('edit-sequence/{id}', 'SlidersController@edit_sequence')->name('edit-sequence');
        Route::PUT('update-sequence/{id}', 'SlidersController@update_sequence')->name('update-sequence');
        Route::get('slider-restore/{id}', 'SlidersController@restore_slider')->name('slider-restore');
        Route::get('slider-deleted', 'SlidersController@get_deleted_slider')->name('sliders.deleted');



    });
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

$langObj = new \Mcamara\LaravelLocalization\LaravelLocalization();
Route::group( ['namespace' => 'Web' , 'middleware' =>['localeSessionRedirect', 'localizationRedirect'] ,'prefix' => $langObj->setLocale()
], function () {

    // Routing Index , Home Page
    Route::get('/', 'IndexController@index')->name("index_home_page");

    // Routing Login , Register
    Route::get('/login-page', 'LoginController@get_login_page')->name("login_page");
    Route::get('/register-page', 'RegisterController@get_register_page')->name("register_page");
    Route::post('/login-web', 'LoginController@login_web')->name("loginWeb");
    Route::post('/register-web', 'RegisterController@register_web')->name("registerWeb");
    Route::get('/forget-page', 'LoginController@get_change_page')->name("change_page");
    Route::post('/forget-password-web', 'LoginController@forgetPassword')->name("forget-password");
    Route::post('/change-password-web', 'LoginController@changePassword')->name("change-password");
    Route::get('/verify-page', 'RegisterController@get_verify_page')->name("verify_page");
    Route::post('/verify', 'RegisterController@verifyCode')->name("verify-account");

    // Routing About Us
    Route::get('/about-us', 'AboutUsController@about_us')->name("aboutUs");

    // Routing Terms And Conditions
    Route::get('/terms-conditions', 'TermsController@terms_conditions')->name("terms_conditions");

    // Routing Faqs
    Route::get('/faq', 'FaqsController@faq')->name("faqs");

    // Routing Payment
    Route::get('/pay', 'Payment@pay')->name("pay");

    Route::get('/callback', 'Payment@get_callback')->name("callBack");


    // Routing Products
    Route::get('/products', 'ProductsController@getProducts')->name("get-products");

    //  Routing Coupons
    Route::get('/coupon_list', 'Coupon@get_coupons')->name("coupon-list");

    // Routing How It Works
    Route::get('/how-it-works', 'HowItWorksController@how_it_works')->name("howItWorks");

    //  Routing Carts
    Route::get('/carts', 'OrdersController@get_orders')->name("get-carts");
    Route::post('add-cart/{id}', 'OrdersController@add_to_cart')->name('add-to-cart');
    Route::post('promo-code', 'OrdersController@apply_promo_code')->name('promo_code');
    Route::get('delete-order/{id}', 'OrdersController@delete_order')->name('deleteOrder');
    Route::get('/all-orders', 'OrdersController@get_all_orders')->name("all_orders");

    //  Routing Profiles
    Route::get('/profile', 'ProfilesController@getProfile')->name("get-profile");
    Route::post('profile-update', 'ProfilesController@update_profile')->name('profile_update');

    //  Routing Profiles
    Route::get('/get_wishlist', 'Wishlists@get_wish_list')->name("wish-list");
    Route::post('/add_to_wishlist', 'Wishlists@Add_To_Wishlist')->name("add-to-wishlist");
    Route::post('/remove_from_wishlist', 'Wishlists@Remove_From_Wishlist')->name("remove-from-wishlist");
    // Route::post('profile-update', 'Wishlist@update_profile')->name('profile_update');


    // Routing Log Out
    Route::get('logOut', 'LogOutController@log_out')->name("log-out");


    // Routing Mobile Pages
    Route::get('about-us-mobile', 'Mobile@about_us_mobile');
    Route::get('how-it-works-mobile', 'Mobile@how_it_works_mobile');
    Route::get('terms-mobile', 'Mobile@terms_mobile');


    // Routing Contact us
    Route::get('/get-contact-us', 'ContactUsController@get_contact_us_page')->name("contactUs");
    Route::post('/contact-us', 'ContactUsController@contact_us')->name("storeContactUs");


    Route::patch("update-order-quantity", "OrdersController@updateOrderQuantity");
    Route::patch("update-order-coupon", "OrdersController@updateOrderCoupon");
    Route::patch("update-number-coupon", "OrdersController@updateCouponNumbers");
    Route::patch("decrease-coupon", "OrdersController@decreaseCoupon");

    Route::get("save-currency/{currency}", "IndexController@saveCurrency");
    Route::get("get-currency", "OrdersController@getCurrency");

app/models/Reward.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Reward extends Model
{
    use SoftDeletes;

    protected $table = "rewards";
    protected $fillable = ["name", "description", "image", "product_id", "attributes_name", "attributes_values"];

    public function product()
    {
        return $this->hasOne(Product::class, "id");
    }
}

app/Http/Controllers/Admin/RewardsController.php
<?php

namespace App\Http\Controllers\Admin;

use File;
use App\models\Product;
use App\models\Reward;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\rewards\create_reward_request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class RewardsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $login_user = Auth::user();
        $rewards = Reward::paginate(5);

        return view("admin.rewards.index", compact("rewards", "login_user"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $reward = null;
        $products = Product::all();
        return view("admin.rewards.create", compact("products", "reward"));
    }


    public function get_deleted_reward()
    {
        $login_user = Auth::user();
        $rewards = Reward::onlyTrashed()->paginate(5);
        return view("admin.rewards.deletedReward", compact("rewards", "login_user"));
    }

    public function restore_reward($id)
    {
        Reward::withTrashed()->where('id', $id)->restore();
        return redirect(route("rewards.index"))->with(['success' => 'Reward Restored successfully']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(create_reward_request $request)
    {
         Reward::create($request->all());
         $reward_data = Reward::orderBy("id", 'desc')->first();
         $image = null;
         if ($request->image) {
            $file = $request->image;
            $path1 = 'storage/images/rewards';
            $fileName1 = rand() . ".png";
            $success1 = $file->move($path1, $fileName1);
            $image = $fileName1;
        }
        if($image != null){
            $reward_data->image = $image;
            $reward_data->save();
        }

         return redirect(route("rewards.index"))->with(['success' => 'Reward Saved successfully']);
 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $reward = Reward::findOrFail($id);
        return view("admin.rewards.show", compact("reward"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $products = Product::all();
        $reward = Reward::findOrFail($id);
        return view("admin.rewards.edit", compact("reward", "products"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        try {
            DB::beginTransaction();
            $reward = Reward::findOrFail($id);

            $image = null;
            if ($request->image) {
                $file = $request->image;
                $path1 = 'storage/images/rewards';
                $fileName1 = rand() . ".png";
                $success1 = $file->move($path1, $fileName1);
                $image = $fileName1;
            }

            $data = $request->all();
            if($image != null){

                $destinationPath = 'storage/images/rewards/'.$reward->image;
                if(File::exists($destinationPath)) {
                    File::delete($destinationPath);            
                }

                $data['image'] = $image;
            }
            $reward->update($data);
            DB::commit();
        } catch (Exception $e) {
            DB::rollBack();
        }
        return redirect(route("rewards.index"))->with(['success' => 'Reward Updated successfully']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $reward = Reward::findOrFail($id);

        $destinationPath = 'storage/images/rewards/'.$reward->image;
        if(File::exists($destinationPath)) {
            File::delete($destinationPath);            
        }

        $reward->delete();
        return redirect(route("rewards.index"))->with(['success' => 'Reward Deleted successfully']);
    }
}

resources/views/admin/rewards/create.blade.php
@extends('admin.layouts.dashboard')

@section("title")
Create New Reward
@endsection

@section('content')


    <!-- Content Header (Page header) -->
    <section class="content-header">

        <!-- <h1>
            Add user
        </h1> -->
        <a class="btn btn-info" href="{{route("rewards.index")}}">
            Back
        </a>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{route('rewards.index')}}"><i class="fa fa-users"></i>Rewards</a></li>
            <li class="active">Add New Reward</li>
        </ol>
    </section>




    <!-- Main content -->
    <section class="content" style="margin-top:1%;">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add New Reward </h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->

                    {!! Form::open(['url'=>route('rewards.store'),'method'=>'post','files'=>true]) !!}

                    @include('admin.rewards.form')
                </div>
                <!-- /.box -->


            </div>
        </div>
    </section>


@stop

resources/views/admin/rewards/deletedReward.blade.php
@extends('admin.layouts.dashboard')

@section("title")
    All Rewards Data
@endsection
@section('content')


    <!-- Content Header (Page header) -->
    <section class="content-header">

        <a class="btn btn-info" href="{{route("rewards.index")}}">
            Back
        </a>
        {{-- @endcan--}}
        {{-- @endpermission--}}
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>

            <li class="active">Rewards</li>
        </ol>
    </section>
    <section class="content">

        @include('admin.layouts.messages')
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body table-responsive ">
                    <table class="table table-hover">
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Description</th>
                        <th>Created At</th>
                        <th>Action</th>
                    </tr>
                    @foreach($rewards as $reward )
                        <tr>
                            <td>{{$reward->id}}</td>
                            <td>{{$reward->name}}</td>
                            <td>{{$reward->image}}</td>
                            @if($reward->product)
                            <td>{{$reward->product->name}}</td>
                            @else
                            <td>No Product </td>
                            @endif
                            <td>{{$reward->description}}</td>
                            <td>{{$reward->created_at->toFormattedDateString()}}</td>

                            <td>
                                <a title="Restore" href="{{route('reward-restore',$reward->id)}}">
                                    <i class="fa fa-window-restore text-info" ></i>
                                </a>
                            </td>

                        </tr>
                    @endforeach
                </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="text-center">
                        {{$rewards->render()}}
                    </div>
                </div>
                <!-- /.box -->
            </div>
        </div>

    </section>


@stop

resources/views/admin/rewards/edit.blade.php
@extends('admin.layouts.dashboard')

@section("title")
    Edit Reward Data
@endsection
@section('content')


    <!-- Content Header (Page header) -->
    <section class="content-header">

        <!-- <h1>
            Edit user
        </h1> -->
        <a class="btn btn-info" href="{{route("rewards.index")}}">
            Back
        </a>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{route('rewards.index')}}"><i class="fa fa-users"></i>Products</a></li>
            <li class="active">Edit Reward Data</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content" style="margin-top: 5%;">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Reward</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->

                    {!! Form::model($reward,['url'=>route('rewards.update',$reward->id),'method'=>'put','files'=>true]) !!}
                    @include("admin.rewards.form")

                </div>
                <!-- /.box -->


            </div>
        </div>
    </section>



@stop

resources/views/admin/rewards/form.blade.php
@include('admin.layouts.messages')

@csrf

<div class="box-body">
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Name</label>
                {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'eg.mercedes Benz']) !!}
            </div>
        </div>

        <div class="col-sm-6">
            <div class="form-group">
                <label for="exampleInputEmail1">Products</label>
                <div>
                    <select class="form-control" name="product_id" required>
                        <option disabled readonly>Product Name</option>
                        @if($products)
                            @foreach($products as $product)
                                <option value="{{$product->id}}">{{$product->name}}</option>
                            @endforeach
                        @endif
                    </select>
                </div>
            </div>
        </div>
    </div>


    <div class="row">
        
        @if($reward == null)

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="exampleInputPassword1">Description</label>
                    {!! Form::textarea('description',null,['class'=>'form-control','placeholder'=>'Enter a description','rows'=>'3'])
                    !!}
                </div>
            </div>


            @else
            <div class="col-sm-12">
                <div class="form-group">
                    <label for="exampleInputPassword1">Description</label>
                    {!! Form::textarea('description',null,['class'=>'form-control','placeholder'=>'Enter a description','rows'=>'3'])
                    !!}
                </div>
            </div>
        @endif
    </div>

    <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="exampleInputEmail1">Attribute Name</label>
                    {!! Form::text('attributes_name',null,['class'=>'form-control','placeholder'=>'eg.Specs , Color ']) !!}
                </div>
            </div>                

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="exampleInputEmail1">Attribute Values</label>
                    {!! Form::text('attributes_values',null,['class'=>'form-control','placeholder'=>'eg.Good , Green  ']) !!}
                </div>
            </div>                

            <div class="col-sm-6">
                <div class="form-group">
                    <label for="exampleInputFile">Image</label>
                    <input type="file" id="exampleInputFile" name="image">
                    <p class="help-block">Please upload a Products pictures</p>
                </div>
            </div>

    </div>                    

</div>
<!-- /.box-body -->

<div class="box-footer">
    <button type="submit" class="btn btn-primary" style="margin-bottom: 3%;
    margin-top: 3%;float: right; position: relative;
    right: 10%;">Submit
    </button>
</div>
</form>

resources/views/admin/rewards/index.blade.php
@extends('admin.layouts.dashboard')

@section("title")
    All Rewards Data
@endsection
@section('content')


    <!-- Content Header (Page header) -->
    <section class="content-header">

        {{--@can('update_user')--}}
        {{--@permission('reward.create')--}}
        @if($login_user->can('create_reward'))

            <a class="btn btn-success" href="{{route('rewards.create')}}">
                Add New Reward
            </a>
            <a class="btn btn-warning" href="{{route('reward.deleted')}}">
                Deleted Reward
            </a>
        @endif
        {{-- @endcan--}}
        {{-- @endpermission--}}
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>

            <li class="active">Rewards</li>
        </ol>
    </section>
    <section class="content">
        @include('admin.layouts.messages')
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body table-responsive ">
                        <table class="table table-hover">
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Image</th>
                                <th>Product</th>
                                <th>Description</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                            @foreach($rewards as $reward )
                                <tr>
                                    <td>{{$reward->id}}</td>
                                    <td>{{$reward->name}}</td>
                                    <td><img width="75px" height="75px" src="{{ url("storage/images/rewards")."/".$reward->image }}" alt=""></td>
                                    @if($reward->product)
                                    <td>{{$reward->product->name}}</td>
                                    @else
                                    <td>No Product </td>
                                    @endif
                                    <td>{{$reward->description}}</td>
                                    <td>{{$reward->created_at->toFormattedDateString()}}</td>
                                    <td>


                                        @if($login_user->can('delete_reward'))
                                        <a data-toggle="modal" data-target="#modal{{$reward->id}}" href="#">
                                                <i class="fa fa-times text-danger"></i>
                                            </a> &nbsp;
                                        @endif&nbsp;
                                        @if($login_user->can('update_reward'))
                                        <a href="{{route('rewards.edit',$reward->id)}}">
                                                <i class="fa fa-edit text-info"></i>
                                            </a> &nbsp;

                                        @endif&nbsp;
                                        @if($login_user->can('view_reward'))
                                        <a href="{{route('rewards.show',$reward->id)}}">
                                                <i class="fa fa-eye text-info"></i>
                                            </a> &nbsp;

                                        @endif&nbsp;
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="text-center">
                        {{$rewards->render()}}
                    </div>
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.content -->
        @foreach($rewards as $reward)
            <div class="modal fade" id="modal{{$reward->id}}" tabindex="-1" supplier="dialog"
                 aria-labelledby="modal{{$reward->id}}" aria-hidden="true">
                <form method="post" action="{{route('rewards-delete',$reward->id)}}">
                    @csrf
                    <div class="modal-dialog" supplier="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Delete {{$reward->name}}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                <p>Are you sure to delete {{$reward->name}} ?</p>


                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-danger">Yes</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        @endforeach
    </section>
@stop