routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/getApp', 'Admin\CareersController@getData');

Route::group(['middleware' => 'auth'], function () {

    Route::get('/admin-panel', 'Admin\DashboardController@index');

    Route::group(['middleware' => ['auth'], 'prefix' => "admin-panel", 'namespace' => 'Admin'], function () {


        // Routing Users
        Route::resource('/users', 'UserController');
        Route::post('user-delete/{id}', 'UserController@destroy')->name("user-delete");
        Route::get('user-restore/{id}', 'UserController@restore_user')->name('user-restore');
        Route::get('user-deleted', 'UserController@get_deleted_user')->name('users.deleted');

        // Routing Coupons
        Route::resource('/coupons', 'CouponsController');
        Route::post('coupon_delete/{id}', 'CouponsController@destroy')->name("coupon-delete");
        Route::get('coupon-restore/{id}', 'CouponsController@restore_coupon')->name('coupon-restore');
        Route::get('coupon-deleted', 'CouponsController@get_deleted_coupon')->name('coupon.deleted');


        // Routing Careers
        Route::resource('/careers', 'CareersController');
        Route::post('career-delete/{id}', 'CareersController@destroy')->name("career-delete");
        Route::get('career-restore/{id}', 'CareersController@restore_career')->name('career-restore');
        Route::get('career-deleted', 'CareersController@get_deleted_career')->name('career.deleted');


        // Routing Career Applicant
        Route::resource('/career-applicant', 'CareerApplicantsController');
        Route::post('career-applicant-delete/{id}', 'CareerApplicantsController@destroy')->name("career-applicant-delete");
        Route::get('career-applicant.download/{id}', 'CareerApplicantsController@download')->name("career-applicant.download");
        Route::get('career-applicant-restore/{id}', 'CareerApplicantsController@restore_career_applicant')->name('career-applicant-restore');
        Route::get('career-applicant-deleted', 'CareerApplicantsController@get_deleted_career_applicant')->name('career-applicant.deleted');


        // Routing Users
        Route::resource('/authorization', 'AuthorizationController');
        Route::post('authorization-delete/{id}', 'AuthorizationController@destroy')->name("authorization-delete");

        // Routing Winners
        Route::post('winners', 'winners@winners')->name("get-winner");
        Route::get('get-winner', 'winners@get_winner')->name("get-all-winner");


        // Routing Categories
        Route::resource('/categories', 'CategoryController');
        Route::post('category-delete/{id}', 'CategoryController@destroy')->name("categories-delete");
        Route::get('category-restore/{id}', 'CategoryController@restore_category')->name('category-restore');
        Route::get('category-deleted', 'CategoryController@get_deleted_category')->name('category.deleted');

        // Routing Offers
        Route::resource('/offers', 'OffersController');
        Route::post('offer-delete/{id}', 'OffersController@destroy')->name("offers-delete");
        Route::get('offer-restore/{id}', 'OffersController@restore_offer')->name('offer-restore');
        Route::get('offer-deleted', 'OffersController@get_deleted_offer')->name('offer.deleted');

        // Routing Donations
        Route::get('/donations', 'DonationController@index')->name("donation");


        // Routing Subscribers
        Route::resource('/messages', 'MessagesController');
        Route::post('message-delete/{id}', 'MessagesController@destroy')->name("messages-delete");

        // Routing Settings
        Route::get('settings/edit', 'SettingController@edit')->name("settings.edit");
        Route::post('settings/update', 'SettingController@update')->name("settings.update");


        // Routing Products
        Route::resource('/products', 'ProductsController');
        Route::post('product-delete/{id}', 'ProductsController@destroy')->name("products-delete");
        Route::PUT('image_update/{id}', 'ProductsController@uploadImages')->name('image.upload');
        Route::get('image_delete/{id}', 'ProductsController@deleteImage')->name('image.delete');
        Route::get('product-restore/{id}', 'ProductsController@restore_product')->name('product-restore');
        Route::get('product-deleted', 'ProductsController@get_deleted_product')->name('product.deleted');

        // Routing Rewards
        
        Route::resource('/rewards', 'RewardsController');
        Route::post('reward-delete/{id}', 'RewardsController@destroy')->name("rewards-delete");
        Route::get('reward-restore/{id}', 'RewardsController@restore_reward')->name('reward-restore');
        Route::get('reward-deleted', 'RewardsController@get_deleted_reward')->name('reward.deleted');

        // Routing Sliders
        Route::resource('/sliders', 'SlidersController');
        Route::post('slider-delete/{id}', 'SlidersController@destroy')->name("sliders-delete");
        Route::PUT('imageSlider_update/{id}', 'SlidersController@upload_Images')->name('imageSlider.upload');
        Route::get('imageSlider_delete/{id}', 'SlidersController@delete_Image')->name('imageSlider.delete');
        Route::get('edit-sequence/{id}', 'SlidersController@edit_sequence')->name('edit-sequence');
        Route::PUT('update-sequence/{id}', 'SlidersController@update_sequence')->name('update-sequence');
        Route::get('slider-restore/{id}', 'SlidersController@restore_slider')->name('slider-restore');
        Route::get('slider-deleted', 'SlidersController@get_deleted_slider')->name('sliders.deleted');



    });
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('locale/{locale}', function ($locale) {
    Session::put('locale', $locale);
    return redirect()->back();
});

$langObj = new \Mcamara\LaravelLocalization\LaravelLocalization();
Route::group( ['namespace' => 'Web' , 'middleware' =>['localeSessionRedirect', 'localizationRedirect'] ,'prefix' => $langObj->setLocale()
], function () {

    // Routing Index , Home Page
    Route::get('/', 'IndexController@index')->name("index_home_page");

    // Routing Login , Register
    Route::get('/login-page', 'LoginController@get_login_page')->name("login_page");
    Route::get('/register-page', 'RegisterController@get_register_page')->name("register_page");
    Route::post('/login-web', 'LoginController@login_web')->name("loginWeb");
    Route::post('/register-web', 'RegisterController@register_web')->name("registerWeb");
    Route::get('/forget-page', 'LoginController@get_change_page')->name("change_page");
    Route::post('/forget-password-web', 'LoginController@forgetPassword')->name("forget-password");
    Route::post('/change-password-web', 'LoginController@changePassword')->name("change-password");
    Route::get('/verify-page', 'RegisterController@get_verify_page')->name("verify_page");
    Route::post('/verify', 'RegisterController@verifyCode')->name("verify-account");

    // Routing About Us
    Route::get('/about-us', 'AboutUsController@about_us')->name("aboutUs");

    // Routing Terms And Conditions
    Route::get('/terms-conditions', 'TermsController@terms_conditions')->name("terms_conditions");

    // Routing Faqs
    Route::get('/faq', 'FaqsController@faq')->name("faqs");

    // Routing Payment
    Route::get('/pay', 'Payment@pay')->name("pay");

    Route::get('/callback', 'Payment@get_callback')->name("callBack");


    // Routing Products
    Route::get('/products', 'ProductsController@getProducts')->name("get-products");

    //  Routing Coupons
    Route::get('/coupon_list', 'Coupon@get_coupons')->name("coupon-list");

    // Routing How It Works
    Route::get('/how-it-works', 'HowItWorksController@how_it_works')->name("howItWorks");

    //  Routing Carts
    Route::get('/carts', 'OrdersController@get_orders')->name("get-carts");
    Route::post('add-cart/{id}', 'OrdersController@add_to_cart')->name('add-to-cart');
    Route::post('promo-code', 'OrdersController@apply_promo_code')->name('promo_code');
    Route::get('delete-order/{id}', 'OrdersController@delete_order')->name('deleteOrder');
    Route::get('/all-orders', 'OrdersController@get_all_orders')->name("all_orders");

    //  Routing Profiles
    Route::get('/profile', 'ProfilesController@getProfile')->name("get-profile");
    Route::post('profile-update', 'ProfilesController@update_profile')->name('profile_update');

    //  Routing Profiles
    Route::get('/get_wishlist', 'Wishlists@get_wish_list')->name("wish-list");
    Route::post('/add_to_wishlist', 'Wishlists@Add_To_Wishlist')->name("add-to-wishlist");
    Route::post('/remove_from_wishlist', 'Wishlists@Remove_From_Wishlist')->name("remove-from-wishlist");
    // Route::post('profile-update', 'Wishlist@update_profile')->name('profile_update');


    // Routing Log Out
    Route::get('logOut', 'LogOutController@log_out')->name("log-out");


    // Routing Mobile Pages
    Route::get('about-us-mobile', 'Mobile@about_us_mobile');
    Route::get('how-it-works-mobile', 'Mobile@how_it_works_mobile');
    Route::get('terms-mobile', 'Mobile@terms_mobile');


    // Routing Contact us
    Route::get('/get-contact-us', 'ContactUsController@get_contact_us_page')->name("contactUs");
    Route::post('/contact-us', 'ContactUsController@contact_us')->name("storeContactUs");


    Route::patch("update-order-quantity", "OrdersController@updateOrderQuantity");
    Route::patch("update-order-coupon", "OrdersController@updateOrderCoupon");
    Route::patch("update-number-coupon", "OrdersController@updateCouponNumbers");

app/models/CareerApplicant.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CareerApplicant extends Model
{
    use SoftDeletes;
    protected $table = "career_applicants";
    protected $fillable = ["first_name","last_name","career_id","file","description","email","phone"];

    public function careers()
    {
        return $this->belongsTo(Career::class , "career_id");
    }
}

app/Http/Controllers/Admin/CareerApplicantsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\models\CareerApplicant;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class CareerApplicantsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $login_user = Auth::user();
        $career_applicants = CareerApplicant::paginate(5);
        return view("admin.career_applicants.index", compact("career_applicants", "login_user"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function get_deleted_career_applicant()
    {
        $login_user = Auth::user();
        $career_applicants = CareerApplicant::onlyTrashed()->paginate(5);
        return view("admin.career_applicants.deletedCareerApplicant", compact("career_applicants", "login_user"));
    }

    public function restore_career_applicant($id)
    {
        CareerApplicant::withTrashed()->where('id',$id)->restore();
        return redirect(route("careers.index"))->with(['success' => 'Career Restored successfully']);
    }

    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    public function download($id)
    {
        $cv = CareerApplicant::findOrFail($id);
        $cv->status = 1 ;
        $cv->save();
        $file= public_path(). "\storage\images\career_applicants/".$cv->file;
        $headers = [
            'Content-Type' => 'application/pdf',
        ];
        return response()->download($file, $cv->file, $headers);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $career_applicant = CareerApplicant::findOrFail($id);
        return view("admin.career_applicants.show", compact("career_applicant"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $career_applicant = CareerApplicant::findOrFail($id);
        $career_applicant->delete();
        return redirect(route("career-applicant.index"))->with(['success' => 'Career Applicant Deleted successfully']);
    }
}

resources/views/admin/career_applicants/create.blade.php
@extends('admin.layouts.dashboard')

@section("title")
Create New Career Applicant
@endsection

@section('content')


    <!-- Content Header (Page header) -->
    <section class="content-header">

        <!-- <h1>
            Add user
        </h1> -->

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{route('career-applicant.index')}}"><i class="fa fa-users"></i>Career Applicant</a></li>
            <li class="active">Add New Career Applicant</li>
        </ol>
    </section>




    <!-- Main content -->
    <section class="content" style="margin-top: 5%;">
        <div class="row">
            <!-- left column -->
            <div class="col-md-10 col-md-offset-1">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Add New Career Applicant </h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->


                    {!! Form::open(['url'=>route('career-applicant.store'),'method'=>'post','files'=>true]) !!}

                    @include('admin.career_applicants.form')
                </div>
                <!-- /.box -->


            </div>
        </div>
    </section>


@stop

resources/views/admin/career_applicants/deletedCareerApplicant.blade.php
@extends('admin.layouts.dashboard')

@section("title")
    All Career Applicant Data
@endsection
@section('content')


    <!-- Content Header (Page header) -->
    <section class="content-header">

        <a class="btn btn-info" href="{{route("career-applicant.index")}}">
            Back
        </a>
        {{-- @

        {{--@can('update_user')--}}
        {{--@permission('user.create')--}}
    {{--    @if($login_user->can('create_career'))

            <a class="btn btn-success" href="{{route('career-applicant.create')}}">
                Add New Career Applicant
            </a>
        @endif--}}
        {{-- @endcan--}}
        {{-- @endpermission--}}
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>

            <li class="active">Career Applicant</li>
        </ol>
    </section>
    <section class="content">

        @include('admin.layouts.messages')
        <div class="row">
            <div class="col-md-offset-1 col-md-10">
                <div class="box">
                    <div class="box-body table-responsive ">
                        <table class="table table-hover">
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>phone</th>
                                <th>Career</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                            @foreach($career_applicants as $career )
                                <tr>
                                    <td>{{$career->id}}</td>
                                    <td>{{$career->first_name}} - {{$career->last_name}}</td>
                                    <td>{{$career->email}}</td>
                                    <td>{{$career->phone}}</td>
                                    @if($career->careers)
                                        <td>{{$career->careers->title}}</td>
                                    @else
                                        <td>No Career</td>
                                    @endif
                                    @if($career ->status == 1)
                                        <td style="color: green" class="edit_data">Viewed</td>
                                    @else
                                        <td style="color: red" class="edit_data">Pending</td>
                                    @endif
                                    <td>{{$career->created_at->toFormattedDateString()}}</td>
                                    <td>
                                        <a title="Restore" href="{{route('career-applicant-restore',$career->id)}}">
                                            <i class="fa fa-window-restore text-info" ></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="text-center">
                        {{$career_applicants->render()}}
                    </div>
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.content -->


    </section>


@stop

resources/views/admin/career_applicants/edit.blade.php
@extends('admin.layouts.dashboard')

@section("title")
    Edit Career Applicant Data
@endsection
@section('content')


    <!-- Content Header (Page header) -->
    <section class="content-header">

        <!-- <h1>
            Edit user
        </h1> -->

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{route('career-applicant.index')}}"><i class="fa fa-users"></i>Career Applicants</a></li>
            <li class="active">Edit Career Applicant Data</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content" style="margin-top: 5%;">
        <div class="row">
            <!-- left column -->
            <div class="col-md-10 col-md-offset-1">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Career Applicant</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->

                    {!! Form::model($career,['url'=>route('career-applicant.update',$career_applicant->id),'method'=>'put','files'=>true]) !!}
                    @include("admin.career_applicants.form")

                </div>
                <!-- /.box -->


            </div>
        </div>
    </section>



@stop

resources/views/admin/career_applicants/form.blade.php
@include('admin.layouts.messages')

@csrf

<div class="box-body">
    <div class="row">
        <div class="col-sm-5">
            <div class="form-group">
                <label for="exampleInputEmail1">First</label>
                {!! Form::text('title',null,['class'=>'form-control','placeholder'=>'eg.I Phone']) !!}
            </div>
        </div>

        <div class="col-sm-5">
            <div class="form-group">
                <label for="exampleInputEmail1">Address</label>
                {!! Form::text('address',null,['class'=>'form-control','placeholder'=>'eg.Describe Job ']) !!}
            </div>
        </div>
    </div>

    <div class="row">
            <div class="col-sm-10">
                <div class="form-group">
                    <label for="exampleInputPassword1">Description</label>
                    {!! Form::textarea('description',null,['class'=>'form-control','placeholder'=>'Enter a description','rows'=>'4'])
                    !!}
                </div>
            </div>
    </div>
    <div class="row">
        <div class="col-sm-5">
            <div class="form-group">
                <label>
                    @if($career)
                        @if($career->status == 1)
                            <input type="checkbox" checked id="exampleInputFile" name="status">
                        @else
                            <input type="checkbox" id="exampleInputFile" name="status"> &nbsp;&nbsp;
                        @endif
                    @endif

                    @if($career == null)
                        <input type="checkbox" id="exampleInputFile" name="status"> &nbsp;&nbsp;
                    @endif
                    Status
                </label>
            </div>
        </div>
    </div>

</div>
<!-- /.box-body -->

<div class="box-footer">
    <button type="submit" class="btn btn-primary" style="margin-bottom: 3%;
    margin-top: 3%;float: right; position: relative;
    right: 10%;">Submit
    </button>
</div>
</form>

resources/views/admin/career_applicants/index.blade.php
@extends('admin.layouts.dashboard')

@section("title")
    All Career Applicant Data
@endsection
@section('content')


    <!-- Content Header (Page header) -->
    <section class="content-header">

        {{--@can('update_user')--}}
        {{--@permission('user.create')--}}
    {{--    @if($login_user->can('create_career'))

            <a class="btn btn-success" href="{{route('career-applicant.create')}}">
                Add New Career Applicant
            </a>
        @endif--}}
        {{-- @endcan--}}
        {{-- @endpermission--}}
        <a class="btn btn-warning" href="{{route('career-applicant.deleted')}}">
            Deleted Career Applicant
        </a>

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>

            <li class="active">Career Applicant</li>
        </ol>
    </section>
    <section class="content">

        @include('admin.layouts.messages')
        <div class="row">
            <div class="col-md-offset-1 col-md-10">
                <div class="box">
                    <div class="box-body table-responsive ">
                        <table class="table table-hover">
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>phone</th>
                                <th>Career</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                            @foreach($career_applicants as $career )
                                <tr>
                                    <td>{{$career->id}}</td>
                                    <td>{{$career->first_name}} - {{$career->last_name}}</td>
                                    <td>{{$career->email}}</td>
                                    <td>{{$career->phone}}</td>
                                    @if($career->careers)
                                    <td>{{$career->careers->title}}</td>
                                    @else
                                    <td>No Career</td>
                                    @endif
                                    @if($career ->status == 1)
                                        <td style="color: green" class="edit_data">Viewed</td>
                                    @else
                                        <td style="color: red" class="edit_data">Pending</td>
                                    @endif
                                    <td>{{$career->created_at->toFormattedDateString()}}</td>
                                    <td>
                                        @if($login_user->can('delete_career_applicant'))
                                            <a data-toggle="modal" data-target="#modal{{$career->id}}" href="#">
                                                <i class="fa fa-times text-danger"></i>
                                            </a> &nbsp;
                                        @endif&nbsp;

                                            <a href="{{route('career-applicant.download',$career->id)}}">
                                                <i class="fa fa-download text-info"></i>
                                            </a> &nbsp;

                                        @if($login_user->can('view_career_applicant'))
                                            <a href="{{route('career-applicant.show',$career->id)}}">
                                                <i class="fa fa-eye text-info"></i>
                                            </a> &nbsp;
                                        @endif&nbsp;
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="text-center">
                        {{$career_applicants->render()}}
                    </div>
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.content -->
        @foreach($career_applicants as $career)
            <div class="modal fade" id="modal{{$career->id}}" tabindex="-1" supplier="dialog"
                 aria-labelledby="modal{{$career->id}}" aria-hidden="true">
                <form method="post" action="{{route('career-applicant-delete',$career->id)}}">
                    @csrf
                    <div class="modal-dialog" supplier="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Delete {{$career->first_name}} - {{ $career->last_name }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                <p>Are you sure to delete {{$career->first_name}} - {{ $career->last_name }} ?</p>


                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-danger">Yes</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>



        @endforeach


    </section>


@stop

resources/views/admin/career_applicants/show.blade.php
@extends('admin.layouts.dashboard')

@section('style')

    <style>
        .edit_data {
            margin-left: 13px;
        }
    </style>

@stop

@section('content')


    <!-- Content Header (Page header) -->
    <section class="content-header">

        <h1>
            Show Career Applicant Data
        </h1>

        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="{{route('career-applicant.index')}}"><i class="fa fa-users"></i> Career Applicant</a></li>
            <li class="active">Add New Career</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-10 col-md-offset-1">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Career Applicant Info</h3>
                    </div>

                    <div class="box-body">
                        <div class="form-group col-md-6">
                            <label for="exampleInputEmail1">First Name</label><br/>
                            <span class="edit_data">{{$career_applicant->first_name}}</span>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="exampleInputEmail1">Last Name</label><br/>
                            <span class="edit_data">{{$career_applicant->last_name}}</span>
                        </div>

                        <div class="clearfix"></div>
                    </div>

                    <div class="box-body">
                        <div class="form-group col-md-6">
                            <label for="exampleInputEmail1">Email</label><br/>
                            <span class="edit_data">{{$career_applicant->email}}</span>
                        </div>

                        <div class="form-group col-md-6">
                            <label for="exampleInputEmail1">Phone</label><br/>
                            <span class="edit_data">{{$career_applicant->phone}}</span>
                        </div>

                        <div class="clearfix"></div>
                    </div>

                    <div class="box-body">
                        <div class="form-group col-md-6">
                            <label for="exampleInputEmail1">Created At</label><br/>
                            <span class="edit_data">{{$career_applicant->created_at->toFormattedDateString()}}</span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="exampleInputEmail1">Status</label><br/>
                            @if($career_applicant ->status == 1)
                                <span style="color: green" class="edit_data">Viewed</span>
                            @else
                                <span style="color: red" class="edit_data">Pending</span>
                            @endif
                        </div>

                        <div class="clearfix"></div>
                    </div>

                    <div class="box-body">
                        <div class="form-group col-md-12">
                            <label for="exampleInputEmail1">Description</label><br/>
                            <span class="edit_data">{{$career_applicant->description}}</span>
                        </div>
                        <div class="clearfix"></div>

                    </div>
                </div>
            </div>
        </div>
    </section>


@stop